### PR TITLE
String.strip is deprecated, replace it with String.trim

### PR DESCRIPTION
**Pull request by Nagasaki45**

### CODE REVIEW

**Comment by iamvery** [comment]
@felipesere this happened [in 1.3](https://github.com/elixir-lang/elixir/blob/v1.3/CHANGELOG.md#3-soft-deprecations-no-warnings-emitted). However, our build still includes 1.2 (thus the test failure). Thoughts?

**Comment by felipesere** [comment]
Is there a way to get numbers from the community about version usage? I'd like to cover 70% of Elixir usage (number pulled out of thin air)

**Comment by iamvery** [comment]
@felipesere i'm not sure. I wonder if https://hex.pm/ would have any insight?

**Comment by felipesere** [comment]
This can be merged once we merge #183

**Comment by felipesere** [comment]
@Nagasaki45 can you rebase `master` into this to ensure CI still passes? We have dropped support for Elixir 1.2 so this should work now.

**Comment by Nagasaki45** [comment]
@felipesere, done! anything else?

**Pull request merged**
