### PR TITLE
Restructure/simplify process koans

### PR DESCRIPTION
**Pull request by iamvery**
While working through the process koans, I found some opportunity to improve the lessons themselves. The changeset is a little noisy, but the story should be relatively clear if read commit-wise.

1. Reword some descriptions
1. Change initial tests to establish baseline: everything's a process, create processes with `spawn`, receive messages with `receive`
1. Get rid of `wait/0` function since it's only used in one place (and might be mistaken for something built-in)
1. Simplify some of the messaging examples by eliminating extra process layers

Also worth mentioning that these examples still suffer from #93, but that should be fixed (or fixable) once we come to a conclusion there.

What do you think?

### CODE REVIEW

**Comment by ukutaht** [comment]
You know I've been thinking that some of these koans, especially:
* koan "Trying to quit normally has no effect"
* koan "Exiting normally yourself on the other hand DOES terminate you"
* koan "Parent processes can be informed about exiting children, if they trap and link"
* koan "If you monitor your children, you'll be automatically informed for their depature"

They seem overly detailed about signal trapping and process monitoring without really teaching what to use processes for.

On the other hand I really like what you've done [here](https://github.com/iamvery/elixir-koans/blob/master/about_processes.exs), especially with the echo loop (and the one before that). What are your thoughts on porting some of those koans over? I feel like they're much better at communicating the idea behind processes without getting into excruciating detail.

**Comment by ukutaht** [comment]
Otherwise, I'm all for all the changes and improved descriptions :+1:

**Comment by iamvery** [comment]
Thanks for the feedback! I'm all for porting stuff over from iamvery/elixir-koans. It's actually on my list of things todo, i.e. run through those and think about what might be useful here. Would you want me to try to do that as part of this PR or another one after merge?

**Comment by ukutaht** [comment]
Awesome. I'll merge this and we can work on porting stuff over in the next PR.

**Comment by iamvery** [comment]
I just realized that porting over https://github.com/iamvery/elixir-koans/blob/7705d743acf3720f75852eb6badfe57f428a3481/about_processes.exs#L50-L64 is going to be problematic cause #94. We could try to address that or just revert to regular `receive` calls for that example.

**Pull request merged**
