### PR TITLE
Change protocol examples

### PR DESCRIPTION
**Pull request by jechol**
I think when struct S implements protocol P, we can say S is P or S has trait of P.
For example, List implements Enumerable and we can say List is Enumerable.

In current example, Musician implements School, but we can't say Musician is School.
I think better abstraction where Musician, Dancer belongs to and Baker doesn't is Artist.

### CODE REVIEW

**Comment by iamvery** [comment]
I don't have a strong opinion about this. @ukutaht @felipesere do you have any thoughts?

**Comment by ukutaht** [comment]
I think the PR does make the example easier to understand. I think we should merge it

**Comment by jechol** [comment]
@ukutaht Could you approve this?

**Comment by ukutaht** [comment]
@jechol merged!

**Pull request merged**
