### PR TITLE
Add koan "You can use pattern matching to define [...]"

### PR DESCRIPTION
**Pull request by s-oram**
Add new koan after discussion in Github issue: 
https://github.com/elixirkoans/elixir-koans/issues/222#issuecomment-399979891

[quote]
And, in fact, you can define multiple cases for a function using this sytnax:

```
lolwat = fn
  "lol" -> "wat"
  _ -> "haha"
end
lolwat.("lol")
# => "wat"
lolwat.("anything")
# => "haha"
lolwat.("rly")
# => "haha"
```

[/quote]

### CODE REVIEW

**Comment by s-oram** [comment]
@felipesere You're right, that does read better. I've renamed the function. Thanks for reviewing the pull request. Is there anything else? :)

**Comment by felipesere** [comment]
Yeah, one key thing is keeping CI happy. 
If you look under /test you can see tests for all Koans. Essentially we ensure that the right answer (or answers) complete the koan. I’m on my phone this instant but I can give you more hints to later if needed 🤓

**Comment by s-oram** [comment]
Thanks guys, I'll take a look at those tests for the CI. :)

**Comment by felipesere** [comment]
Thank you!!!

**Comment by s-oram** [comment]
Thanks Felipe! :)

**Pull request merged**
