### PR TITLE
Some grammar changes

### PR DESCRIPTION
**Pull request by iamvery**
Couple small things. There was also "levelling the playing field" which my computer (and myself) thought was a typo. It seems like it also may be part of my North American english. Happy to send that along as well if it is indeed a fix.

### CODE REVIEW

**Comment by ukutaht** [comment]
Thank you for the contribution! 👍

**Comment by iamvery** [comment]
You're welcome! Did you have any opinion/input on "levelling"? I'm curious 😄

**Comment by ukutaht** [comment]
Hmm.. I wonder which spelling does Elixir itself favour? Most languages tend to prefer American English (`color` in CSS, `initialize` in Ruby) but I can't recall seeing anything in Elixir that reveals which spelling it prefers.

Overall I don't really mind which spelling we use as long as it's consistent. As most programming languages and programs themselves use American English I think we should just move to that.

So the short answer is that we should probably use 'leveling' and remove any other British spellings from the descriptions.

**Comment by ukutaht** [comment]
For some background, we may have more British expressions/spellings in the koans because pretty much everyone who has contributed to this project lives in London.

**Comment by iamvery** [comment]
It seems Elixir also favors American English (here's a reference to [color](http://elixir-lang.org/docs/stable/elixir/IO.ANSI.html#color/1)). I'm with you, I don't feel strongly either way :). Koans are usually a little whimsical which their wording, so it might even add a nice touch 😊. I'll let you all make those decisions! ❤️ 

I have found a couple other things to work on. I'll probably be sending a few PRs your way :soon:! I'm excited about the project 😃 https://twitter.com/iamvery/status/723874562446884864

**Comment by ukutaht** [comment]
@iamvery Makes sense, I've pushed a change to use the American version ;)

There are still many areas to improve, PRs are greatly appreciated :)

**Comment by iamvery** [comment]
Awesome! I just pushed one 💃

**Pull request merged**
