### PR TITLE
Convert from ExFSWatch to FileSystem

### PR DESCRIPTION
**Pull request by jgandt**
I was going through the koans again (I found myself really needing a refresher) and happened to notice the old package was still in here.

I took a crack at converting it and I did a bit of very basic testing.

Please let me know if there are other changes you would like to see or specific testing I should do.

### CODE REVIEW

**Comment by felipesere** [comment]
Awesome, thank you for this. 
I’ll test this tonight and take a look at the Jenkins failures.

**Comment by ukutaht** [comment]
Thanks for the PR :)

@felipesere I think you're too deep in the corporate consulting world. We run Travis not Jenkins 😄

**Comment by jgandt** [comment]
Nuts. The build is failing but I have no idea why. The application boots as expected when I just run this locally. `mix test` also at least boots and starts running locally (albeit with at least one error).

**Comment by jgandt** [comment]
@felipesere and @ukutaht I could use some help on this PR and why the failures are happening.

**Comment by jgandt** [comment]
Hey there! Just checking to see if you have had a chance to look at these mysteriously failing tests.

**Comment by felipesere** [comment]
Thanks for pinging me about this! I wanted to look into it over Christmas but it got busier than expected (shocker!).

It looks like the new `ExFsWatch` is a bit more sensitive about `inotify-tools` being installed. 

Can you try adding this to the `.travis.yml` at the top? Or grant me access to push commits onto your PR 😄 

```
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y inotify-tools
```

**Comment by iamvery** [comment]
Thanks for getting to this @felipesere 🙌 I too have had good intention to jump in and help. And I too have found excess time a scarce resource 😩

Hope this helps you @jgandt!

**Comment by jgandt** [comment]
Added the `before_install` lines and added Felipe as a collab on this repo. Felipe feel free to go nuts with any changes you want to make.

**Comment by jgandt** [comment]
Please let me know if there are any other changes people would like to see!

Otherwise I think this is ready to merge.

**Pull request merged**
